const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code='// heading\n\nfunction total(x: number) {\n  return x + 1;\n}\n';
const selected=code.slice(code.indexOf('function'));
const positionAt=offset=>{const lines=code.slice(0,offset).split('\n');return {line:lines.length-1,character:lines.at(-1).length};};
const offsetAt=pos=>code.split('\n').slice(0,pos.line).reduce((n,line)=>n+line.length+1,0)+pos.character;
const uri=path=>({scheme:'file',path,toString:()=>`file://${path}`});
const document={languageId:'typescript',version:1,uri:uri('/project/example.ts'),getText:selection=>selection?selected:code,positionAt,offsetAt};
const editor={document,viewColumn:1,selection:{isEmpty:false,start:{line:2,character:0}}};
const commands={},sent=[],revealed=[],errors=[],executed=[];let handler;
const disposable={dispose(){}};
const panel={reveal(){},dispose(){},onDidDispose(){return disposable;},webview:{cspSource:'vscode-webview:',asWebviewUri:uri=>({toString:()=>`vscode-webview:${uri.path}`}),postMessage:message=>sent.push(message),onDidReceiveMessage:fn=>(handler=fn,disposable)}};
const api={Uri:{isUri:value=>value?.scheme==='file',joinPath:(uri,...parts)=>({path:uri.path+'/'+parts.join('/')})},Selection:class{constructor(start,end){this.start=start;this.end=end;}},ViewColumn:{Beside:2,One:1},TextEditorRevealType:{InCenterIfOutsideViewport:1},window:{activeTextEditor:editor,visibleTextEditors:[editor],createWebviewPanel:()=>panel,onDidChangeActiveTextEditor:()=>disposable,showErrorMessage:message=>errors.push(message),showTextDocument:async(doc,options)=>{revealed.push({doc,options});return {revealRange(){}};}},workspace:{fs:{readFile:async()=>Buffer.from(fs.readFileSync('shared/explain.html','utf8'))}},commands:{registerCommand:(id,fn)=>(commands[id]=fn,disposable),executeCommand:async id=>executed.push(id)}};
const sandbox={module:{exports:{}},require:name=>name==='vscode'?api:require(name),Buffer};vm.runInNewContext(fs.readFileSync('extension/explain-panel.js','utf8'),sandbox);const ext=sandbox.module.exports;
(async()=>{
  const snapshot=ext.captureSource(editor);assert.equal(snapshot.offset,12);assert.equal(snapshot.payload.baseLine,3);assert.equal(snapshot.payload.language,'TypeScript');
  api.window.activeTextEditor=undefined;
  ext.activateExplain({extensionUri:{path:'/extension'},subscriptions:[]});await commands['codealive.start']();assert.equal(sent.length,0);
  api.window.activeTextEditor=editor;await commands['codealive.start']();assert.equal(sent.length,0);await handler({type:'ready'});assert.equal(sent[0].code,selected);
  await handler({type:'sourceReceived',sourceToken:sent[0].sourceToken});
  const before=sent.length;
  api.window.activeTextEditor=undefined;await commands['codealive.start']();assert.equal(sent.length,before,'Opening from the panel must not reload the remembered editor');
  const unrelated={...editor,document:{...document,languageId:'markdown',uri:uri('/project/notes.md')}};
  api.window.activeTextEditor=unrelated;await commands['codealive.start']();assert.equal(sent.length,before,'Unsupported files must not replace current work');
  api.window.activeTextEditor={...editor,document:{...document,getText:()=>''}};await commands['codealive.start']();assert.equal(sent.length,before,'Empty source must not replace current work');
  api.window.activeTextEditor=unrelated;await commands['codealive.start'](document.uri);assert.equal(sent.at(-1).code,selected,'A toolbar resource must select its own visible editor');
  const missing=sent.length;await commands['codealive.start'](uri('/project/closed.ts'));assert.equal(sent.length,missing,'A missing toolbar target must not load another editor');
  api.window.activeTextEditor={...editor,selection:{isEmpty:true}};await commands['codealive.start']();assert.equal(sent.at(-1).code,code);assert.equal(sent.at(-1).baseLine,1);
  for(const [id,language] of [['javascript','JavaScript'],['javascriptreact','JavaScript'],['typescript','TypeScript'],['typescriptreact','TypeScript']]){
    api.window.activeTextEditor={...editor,document:{...document,languageId:id}};await commands['codealive.start']();assert.equal(sent.at(-1).language,language);assert.equal(sent.at(-1).code,selected);
  }
  const oversized={...editor,selection:{isEmpty:true},document:{...document,getText:selection=>selection?selected:'x'.repeat(50001)}};
  api.window.activeTextEditor=oversized;const bounded=sent.length;await commands['codealive.start']();assert.equal(sent.length,bounded);assert.match(errors.pop(),/smaller section/);
  oversized.selection=editor.selection;await commands['codealive.start']();assert.equal(sent.at(-1).code,selected,'A small selection in a large file must still load');
  api.window.activeTextEditor=editor;await commands['codealive.explain']();assert.equal(sent.at(-1).code,selected);
  const html=panel.webview.html;assert(html.includes("connect-src 'none'"));assert(!html.includes(selected));assert.equal((html.match(/<script nonce=/g)||[]).length,(fs.readFileSync('shared/explain.html','utf8').match(/<script src=/g)||[]).length);assert(!/<script src=/.test(html));
  await handler({type:'reviewPR',command:'untrusted.command'});assert.deepEqual(executed,['codealive.reviewPR']);
  const payload=sent.at(-1),start=selected.indexOf('return'),end=start+'return x + 1;'.length;
  await handler({type:'revealSource',sourceToken:'invalid',start,end});assert.equal(revealed.length,0);
  await handler({type:'revealSource',sourceToken:payload.sourceToken,start:-1,end});assert.equal(revealed.length,0);
  await handler({type:'revealSource',sourceToken:payload.sourceToken,start,end});assert.equal(revealed.length,1);assert.equal(revealed[0].options.selection.start.line,3);assert.equal(revealed[0].options.selection.start.character,2);
  document.version++;await handler({type:'revealSource',sourceToken:payload.sourceToken,start,end});assert.equal(revealed.length,1);assert(sent.at(-1).text.includes('changed'));
  await commands['codealive.explainText']({code:'function f(){return 2;}',language:'JavaScript'});const standalone=sent.at(-1);await handler({type:'revealSource',sourceToken:standalone.sourceToken,start:1,end:4});assert.equal(revealed.length,1);assert.equal(errors.length,0);
  console.log('Explainer panel: automatic IDE entry, toolbar resource, preserved panel work, limits, selection offsets, ready handshake, CSP and stale-document guards passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
