(function(root){
const samples=[
{title:'Async JavaScript',language:'JavaScript',code:`async function bringCodeToLife(source) {\n  const events = source.split("\\n");\n  for (const event of events) {\n    if (event.includes("function")) {\n      await playMelody(event);\n    } else {\n      pulse(event.length);\n    }\n  }\n  return { soundtrack: "alive" };\n}\n\nbringCodeToLife(myCode);`},
{title:'Python melody',language:'Python',code:`def compose_code(lines):\n    melody = []\n    for index, line in enumerate(lines):\n        if line.strip():\n            note = len(line) % 7\n            melody.append((index, note))\n    return melody\n\nclass Soundtrack:\n    def play(self, melody):\n        for beat, note in melody:\n            print(f"Beat {beat}: {note}")\n\nSoundtrack().play(compose_code(source))`},
{title:'Cloud infrastructure',language:'Terraform',code:`terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws" }\n  }\n}\n\nresource "aws_instance" "soundtrack" {\n  ami           = var.ami_id\n  instance_type = "t3.micro"\n  tags = { Name = "CodeAlive" }\n}\n\noutput "studio_ip" {\n  value = aws_instance.soundtrack.public_ip\n}`},
{title:'Kubernetes pulse',language:'Kubernetes',code:`apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: codealive\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: codealive\n  template:\n    metadata:\n      labels:\n        app: codealive\n    spec:\n      containers:\n        - name: studio\n          image: codealive:latest\n          ports:\n            - containerPort: 8080`},
{title:'React counter',language:'JavaScript',code:`function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      {count} beats\n    </button>\n  );\n}`},
{title:'All tests pass',language:'JavaScript',code:`describe("soundtrack", () => {\n  for (const style of styles) {\n    it("turns code into music", () => {\n      const track = compose(source, style);\n      expect(track.notes.length).toBeGreaterThan(0);\n      expect(track.clipping).toBe(false);\n    });\n  }\n});`},
{title:'Recursive rhythm',language:'Python',code:`def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\nfor number in range(12):\n    print(fibonacci(number))`},
{title:'Bubble sort',language:'Python',code:`def bubble_sort(items):\n    for i in range(len(items)):\n        for j in range(len(items) - i - 1):\n            if items[j] > items[j + 1]:\n                items[j], items[j + 1] = items[j + 1], items[j]\n    return items\n\nprint(bubble_sort([8, 3, 5, 1, 9]))`},
{title:'Terraform fleet',language:'Terraform',code:`resource "aws_instance" "fleet" {\n  for_each = toset(["melody", "rhythm", "bass"])\n  ami = var.ami_id\n  instance_type = "t3.micro"\n  tags = { Name = each.key }\n}\n\nvariable "ami_id" {\n  type = string\n}`},
{title:'Service harmony',language:'Kubernetes',code:`apiVersion: v1\nkind: Service\nmetadata:\n  name: harmony\nspec:\n  selector:\n    app: codealive\n  ports:\n    - port: 80\n      targetPort: 8080\n  type: ClusterIP`}];
function analyze(code){const lines=code.split('\n');const events=lines.map((text,line)=>{const clean=text.replace(/(['"])(?:\\.|(?!\1).)*\1/g,'""').replace(/\/\/.*$|#.*$/,'');let kind=/\b(function|def|class|async)\b|=>/.test(clean)?'melody':/\b(for|while|for_each|replicas)\b/.test(clean)?'rhythm':/\b(if|else|try|catch|except)\b/.test(clean)?'tension':/\b(const|let|var|resource|variable|kind|output)\b/.test(clean)?'bass':'texture';let hash=0;for(const c of text)hash=(hash*31+c.charCodeAt(0))>>>0;return {text,line,kind,note:hash%7,energy:Math.min(1,.25+text.trim().length/80)};}).filter(e=>e.text.trim());return {lines:lines.length,functions:events.filter(e=>e.kind==='melody').length,events};}
function arrange(event,index,style){const scale=[0,2,3,5,7,8,10];const roots=[0,8,3,10];const root=roots[Math.floor(index/8)%4];const chord=[48+root,51+root,55+root];const octave=style==='bit'?12:0;return {melody:60+root+scale[event.note%7]+octave,bass:36+root,chord};}
root.CodeAlive={samples,analyze,arrange};if(typeof module!=='undefined')module.exports=root.CodeAlive;
})(typeof window!=='undefined'?window:globalThis);
