let sortView=null;
const codeDraw=draw,codeStart=start,codeStop=stop,codeLock=lock;
function sortingMode(){return $('performanceMode').value==='sorting'}
function prepareSort(){const trace=CodeAliveSort.trace(CodeAliveSort.parse($('sortValues').value),$('sortKind').value);sortView={trace,index:0};return trace}
function sortSound(e){const base=44+(e.values[Math.max(0,e.i)]||e.values[0])%30;if(e.type==='compare'){voice(base,audio.currentTime,.12,.055,style==='bit'?'square':'sine')}else if(e.type==='swap'){voice(base+12,audio.currentTime,.18,.1,'triangle');drum(audio.currentTime)}else if(e.type==='pivot'){voice(base,audio.currentTime,.3,.08,'triangle')}else if(e.type==='done'){[48,51,55,60].forEach(m=>voice(m,audio.currentTime,1.1,.05,'sine',.08))}}
function silenceSorting(){for(const osc of activeVoices){try{osc.stop()}catch{}}activeVoices.clear()}
lock=function(active){codeLock(active);['performanceMode','sortKind','sortValues','sortReset'].forEach(id=>$(id).disabled=active);$('sortSpeed').disabled=active;$('sortPause').disabled=!!recorder;$('sortStep').disabled=!!recorder};
stop=function(){codeStop();$('sortPause').textContent='Pause'};
start=async function(record=false){if(!sortingMode())return codeStart(record);if(session){stop();return}if(recorder){message('Finishing your recording. Please wait.');return}try{const trace=prepareSort();await initAudio();master.gain.setTargetAtTime(+$('volume').value/100*.55,audio.currentTime,.02);if(record)beginRecording();session={sorting:true,recording:record,events:trace.events,elapsed:0,last:performance.now(),paused:false,timer:null,end:null,duration:record?+$('duration').value:(trace.events.length-1)/+$('sortSpeed').value+1.3};const current=session;lock(true);$('play').textContent='■ Stop';$('state').textContent=record?'RECORDING':'SORTING';$('record').disabled=true;message(record?'Recording every comparison and swap…':'The built-in algorithm is running. Pause or step to inspect it.');sortSound(trace.events[0]);function tick(){if(session!==current)return;const now=performance.now();if(current.paused){current.last=now;return}current.elapsed+=(now-current.last)/1000;current.last=now;const progress=current.recording?Math.max(0,Math.min(1,(current.elapsed/current.duration-.15)/.7)):current.elapsed*+$('sortSpeed').value/(trace.events.length-1);const target=Math.min(trace.events.length-1,Math.floor(progress*(trace.events.length-1)));while(sortView.index<target){sortView.index++;sortSound(trace.events[sortView.index])}if(current.elapsed>=current.duration){stop();if(!record)message(`Sorted. ${trace.comparisons} comparisons · ${trace.swaps} swaps.`)}}current.timer=setInterval(tick,25)}catch(e){stop();message(e.message)}};
$('performanceMode').onchange=()=>{stop();$('sortControls').hidden=!sortingMode();if(sortingMode()){try{prepareSort();message('Choose numbers, then Play, Step, or Record video.')}catch(e){message(e.message)}}};
$('sortKind').onchange=$('sortValues').onchange=()=>{stop();try{prepareSort()}catch(e){message(e.message)}};
$('sortReset').onclick=()=>{stop();try{prepareSort();message('Sorting reset.')}catch(e){message(e.message)}};
$('sortSpeed').oninput=()=>$('sortSpeedLabel').textContent=$('sortSpeed').value+' steps/s';
$('sortPause').onclick=()=>{if(!session?.sorting||session.recording){message('Start a sorting preview to use Pause.');return}session.paused=!session.paused;session.last=performance.now();if(session.paused)silenceSorting();$('sortPause').textContent=session.paused?'Resume':'Pause';$('state').textContent=session.paused?'PAUSED':'SORTING'};
$('sortStep').onclick=async()=>{if(recorder)return;try{if(!sortView)prepareSort();await initAudio();master.gain.setTargetAtTime(+$('volume').value/100*.55,audio.currentTime,.02);if(session?.sorting){session.paused=true;silenceSorting();$('sortPause').textContent='Resume';$('state').textContent='PAUSED'}if(sortView.index<sortView.trace.events.length-1){sortView.index++;if(session?.sorting&&!session.recording)session.elapsed=sortView.index/+$('sortSpeed').value;sortSound(sortView.trace.events[sortView.index])}message(`Step ${sortView.index+1} of ${sortView.trace.events.length}.`)}catch(e){message(e.message)}};
function drawSort(now){ctx.setTransform(2,0,0,2,0,0);ctx.fillStyle='#0b1019';ctx.fillRect(0,0,540,960);const [mint,purple]=palettes[style],view=sortView,e=view?.trace.events[view.index];ctx.fillStyle=mint;ctx.font='bold 18px monospace';ctx.fillText('CODEALIVE / ACTUAL ALGORITHM',38,54);ctx.fillStyle='#eff5fb';ctx.font='bold 34px sans-serif';const name=$('sortKind').value==='bubble'?'Bubble Sort':'Quick Sort';const title=$('videoTitle').value.trim()||`${name}, made audible`;CodeAliveStudio.wrap(title,26).forEach((line,i)=>ctx.fillText(line,38,116+i*42));ctx.fillStyle='#9faebe';ctx.font='16px monospace';ctx.fillText(name+' · BUILT-IN EXECUTION',38,205);
if(!e){ctx.fillStyle=mint;ctx.font='20px sans-serif';ctx.fillText('Enter numbers, then press Play.',38,360);return}const values=e.values,w=440/values.length,max=Math.max(...view.trace.input);for(let i=0;i<values.length;i++){const h=values[i]/max*260;ctx.fillStyle=e.type==='done'?mint:i===e.pivot?purple:i===e.i||i===e.j?'#ffe182':'#355d82';ctx.fillRect(50+i*w,545-h,w-6,h);ctx.fillStyle='#edf5fb';ctx.font='14px monospace';ctx.textAlign='center';ctx.fillText(String(values[i]),50+i*w+(w-6)/2,568)}ctx.textAlign='left';const action=e.type==='compare'?`Compare ${values[e.i]} and ${values[e.j]}`:e.type==='swap'?'Swap the highlighted values':e.type==='pivot'?`Choose pivot ${values[e.pivot]}`:e.type==='partition'?'Pivot reaches its final position':e.type==='done'?'Sorted. Every value is in order.':'Start with an unsorted list';const recording=session?.sorting&&session.recording,progress=recording?session.elapsed/session.duration:0;const caption=recording&&progress<.15?($('hook').value||`Watch ${name} work`):recording&&progress>.85?($('ending').value||'Sorted, with a soundtrack.'):action;ctx.fillStyle=mint;ctx.font='bold 20px sans-serif';CodeAliveStudio.wrap(caption,42).forEach((line,i)=>ctx.fillText(line,38,250+i*24));ctx.fillStyle='#172332';ctx.fillRect(38,610,464,190);ctx.fillStyle='#edf5fb';ctx.font='bold 23px sans-serif';ctx.fillText(action.slice(0,36),56,655);ctx.font='18px monospace';ctx.fillText(`${e.comparisons} comparisons`,56,697);ctx.fillText(`${e.swaps} swaps`,56,730);ctx.fillStyle='#9faebe';ctx.font='14px monospace';ctx.fillText(`STEP ${view.index+1} / ${view.trace.events.length}`,56,770);ctx.fillStyle='#2a3d51';ctx.fillRect(38,845,464,4);ctx.fillStyle=mint;ctx.fillRect(38,845,464*(view.index/(view.trace.events.length-1)),4);ctx.font='16px sans-serif';ctx.fillText($('creator').value,38,888);ctx.fillStyle='#edf5fb';ctx.font='bold 24px sans-serif';ctx.fillText('CODEALIVE',38,925);ctx.fillStyle='#9faebe';ctx.font='14px sans-serif';ctx.fillText('github.com/bvs1006/CodeAlive',215,925)}
draw=function(now){if(sortingMode()){drawSort(now);raf=requestAnimationFrame(draw)}else codeDraw(now)};
