(function(root){
const defaults={soundtrack:['What does this code sound like?','Code structure becomes music and motion.','Make your code alive.'],algorithm:['A rhythm inspired by this algorithm','Loops and conditions shape the performance.','Code structure, turned into a soundtrack.'],project:['A look inside my project','Functions, rhythm, and a little creativity.','Built with code. Performed with CodeAlive.']};
function settings(){const el=id=>document.getElementById(id);return {template:el('videoTemplate').value,hook:el('hook').value,caption:el('caption').value,ending:el('ending').value,videoTitle:el('videoTitle').value,creator:el('creator').value,style:typeof style==='string'?style:'ambient',tempo:+el('tempo').value,duration:+el('duration').value,hideSource:el('hideSource').checked}}
function music(index,total){const p=index/total;return p<.2?{phase:'intro',level:.5}:p<.55?{phase:'build',level:.75}:p<.84?{phase:'peak',level:1}:{phase:'outro',level:.4}}
function scene(p,s){const phase=p<.2?'intro':p<.55?'build':p<.84?'peak':'outro';return {phase,caption:phase==='intro'?s.hook:phase==='outro'?s.ending:s.caption}}
function wrap(text,width){const out=[];let line='';for(const word of text.split(/\s+/)){if((line+' '+word).trim().length>width&&line){out.push(line);line=''}line+=(line?' ':'')+word}if(line)out.push(line);return out.slice(0,2).map(x=>x.length>width?x.slice(0,width-1)+'…':x)}
function template(name){if(!defaults[name])return;['hook','caption','ending'].forEach((id,i)=>document.getElementById(id).value=defaults[name][i]);document.getElementById('templateNote').textContent=name==='algorithm'?'Inspired by algorithm structure. This template does not execute code.':'Music inspired by code structure. Code is not executed.'}
function apply(p){if(typeof session!=='undefined'&&session)return;if(!defaults[p.template]||!['ambient','synth','bit'].includes(p.style))return;document.getElementById('videoTemplate').value=p.template;template(p.template);['hook','caption','ending','videoTitle','creator'].forEach(id=>{if(typeof p[id]==='string')document.getElementById(id).value=p[id].slice(0,80)});document.getElementById('tempo').value=p.tempo;document.getElementById('bpm').textContent=p.tempo+' BPM';document.getElementById('duration').value=p.duration;document.getElementById('durationLabel').textContent=p.duration+'-second session';document.getElementById('hideSource').checked=!!p.hideSource;setStyle(p.style)}
root.CodeAliveStudio={settings,music,scene,wrap,template,apply};if(typeof module!=='undefined')module.exports=root.CodeAliveStudio;
})(typeof window!=='undefined'?window:globalThis);
