apiVersion: apps/v1
kind: Deployment
metadata:
  name: codealive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codealive
  template:
    metadata:
      labels:
        app: codealive
    spec:
      containers:
        - name: studio
          image: codealive:latest
          ports:
            - containerPort: 8080
