(function(root){
  'use strict';
  root.CodeAliveMovieUI={mount({host,getContext,getTrace,onRange}){
    const $=id=>document.getElementById(id),canvas=$('movie-canvas'),ctx=canvas.getContext('2d');
    let context=null,source='',scenes=[],narration=null,narrationName='',generation=0,state=null,blob=null,url=null,mode='explanation',replayInput='',audioLoading=false;
    const status=text=>{$('movie-status').textContent=text;};
    function clearOutput(){blob=null;if(url)URL.revokeObjectURL(url);url=null;$('movie-download').hidden=true;$('movie-preview').removeAttribute('src');$('movie-preview').load();}
    function controls(busy){$('movie-stop').disabled=!busy;for(const el of $('movie-editor').querySelectorAll('input,textarea,select,button'))el.disabled=busy;$('movie-play').disabled=busy||audioLoading||!scenes.length;$('movie-record').disabled=busy||audioLoading||!scenes.length;$('movie-save').disabled=busy||!blob;}
    function cleanup(s){cancelAnimationFrame(s.raf);clearTimeout(s.watchdog);for(const node of s.nodes)try{node.stop();}catch{}s.stream?.getTracks().forEach(t=>t.stop());s.dest.stream.getTracks().forEach(t=>t.stop());s.audio.close().catch(()=>{});if(state===s)state=null;controls(false);}
    function stop(discard=false){const s=state;if(!s)return;s.discard=discard;s.early=!s.finished;cancelAnimationFrame(s.raf);clearTimeout(s.watchdog);for(const node of s.nodes)try{node.stop();}catch{}if(s.recorder&&s.recorder.state!=='inactive')s.recorder.stop();else{cleanup(s);status(discard?'Playback cleared.':'Preview stopped.');}}
    function clear(){generation++;stop(true);clearOutput();context=null;scenes=[];source='';audioLoading=false;narration=null;narrationName='';$('movie-narration').value='';$('movie-audio-status').textContent='No narration loaded.';$('movie-scenes').replaceChildren();$('movie-length').textContent='';$('movie-position').textContent='Ready to preview';ctx.fillStyle='#0b1018';ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#9eafc3';ctx.font='36px sans-serif';ctx.fillText('Build a script to preview a frame.',72,250);$('movie-work').hidden=true;controls(false);status('Explain a function first, then build a script.');}
    function setContext(){const next=getContext();if(!next)return clear();if(context&&next.code===context.code&&next.scopeId===context.scopeId&&next.language===context.language)return;clear();context=next;$('movie-work').hidden=false;status('Choose explanation steps or a captured replay, then build a script.');}
    function readPlan(){return CodeAliveMovie.plan(source,scenes,{title:$('movie-title').value,hideSource:$('movie-hide').checked,mode});}
    function update(){clearOutput();try{const p=readPlan();CodeAliveMovie.draw(ctx,p,0);$('movie-length').textContent=`${p.scenes.length} scenes · ${p.seconds.toFixed(1)} seconds${mode==='replay'?' · Captured input: '+replayInput:''}`;let elapsed=0;for(const [i,s]of scenes.entries()){const out=$('movie-scenes').children[i]?.querySelector('output');if(out)out.textContent=s.enabled?`${elapsed.toFixed(1)}–${(elapsed+Number(s.duration)).toFixed(1)}s`:'Excluded';if(s.enabled)elapsed+=Number(s.duration);}if(narration)audioNote(p);}catch(e){status(e.message);}controls(false);}
    function audioNote(p){$('movie-audio-status').textContent=`${narrationName} · ${narration.duration.toFixed(1)} seconds. ${narration.duration>p.seconds+0.15?'Audio is longer than the video. Fit timing or shorten the audio before recording.':narration.duration<p.seconds-0.15?'Narration ends before the video; remaining scenes will have no voice.':'Narration and video durations match.'}`;}
    function renderScenes(){const list=$('movie-scenes');list.replaceChildren();for(const [i,s]of scenes.entries()){
      const row=document.createElement('div');row.className='movie-scene';const include=document.createElement('input');include.type='checkbox';include.checked=s.enabled;include.setAttribute('aria-label','Include scene '+(i+1));
      const label=document.createElement('label');label.textContent='Scene '+(i+1);label.append(include);const caption=document.createElement('textarea');caption.value=s.caption;caption.maxLength=240;caption.rows=3;caption.setAttribute('aria-label','Caption for scene '+(i+1));const duration=document.createElement('input');duration.type='number';duration.min='0.5';duration.max='15';duration.step='0.1';duration.value=s.duration;duration.setAttribute('aria-label','Seconds for scene '+(i+1));const output=document.createElement('output');
      include.onchange=()=>{s.enabled=include.checked;update();};caption.oninput=()=>{s.caption=caption.value;update();};duration.oninput=()=>{s.duration=Number(duration.value);update();};row.append(label,caption,duration,output);list.append(row);
    }update();}
    $('movie-build').onclick=()=>{try{const current=getContext();if(!current)throw Error('Explain a function first.');mode=$('movie-mode').value;const trace=getTrace(),items=mode==='replay'?trace?.steps:current.model.steps;if(!items?.length)throw Error('Run Replay first to capture a trace.');const start=Number($('movie-first').value),end=Number($('movie-last').value);if(!Number.isInteger(start)||!Number.isInteger(end)||start<1||end<start||end>items.length||end-start>=20)throw Error(`Select 1–20 consecutive steps from the available ${items.length}.`);
      source=current.code;replayInput=mode==='replay'?trace.input:'';scenes=items.slice(start-1,end).map(s=>({enabled:true,duration:3,caption:(mode==='replay'?`${s.kind}${s.detail?': '+s.detail:''}. Value: ${JSON.stringify(s.value)}`:s.beginner).slice(0,240),range:{...(mode==='replay'?s.range:s)}}));renderScenes();status('Edit captions and scene durations, add recorded narration if wanted, then preview.');
    }catch(e){status(e.message);}};
    function stepRange(){const current=getContext(),trace=getTrace(),length=($('movie-mode').value==='replay'?trace?.steps:current?.model.steps)?.length||0;$('movie-first').value=1;$('movie-last').value=Math.min(10,length);$('movie-range-note').textContent=`${length} available steps. Build up to 20 at a time.`;}
    $('movie-mode').onchange=stepRange;$('movie-refresh-steps').onclick=stepRange;
    for(const id of ['movie-title','movie-hide','movie-music'])$(id).addEventListener('input',()=>{if(scenes.length)update();});
    async function audioDuration(file){const temp=URL.createObjectURL(file),audio=document.createElement('audio');try{return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Could not read audio duration. Try a WAV file.')),10000);audio.onloadedmetadata=()=>{clearTimeout(timer);resolve(audio.duration);};audio.onerror=()=>{clearTimeout(timer);reject(Error('Audio metadata could not be read. Try WAV or MP3.'));};audio.src=temp;});}finally{audio.removeAttribute('src');audio.load();URL.revokeObjectURL(temp);}}
    $('movie-narration').onchange=async()=>{const file=$('movie-narration').files[0],id=++generation;narration=null;narrationName='';clearOutput();if(!file){audioLoading=false;controls(!!state);$('movie-audio-status').textContent='No narration loaded.';return;}audioLoading=true;controls(false);let audio;
      try{if(file.size>15*1024*1024)throw Error('Narration must be at most 15 MB.');const duration=await audioDuration(file);if(!Number.isFinite(duration)||duration<=0||duration>120)throw Error('Narration must have a known duration of at most 120 seconds.');if(id!==generation)return;
        audio=new AudioContext({sampleRate:48000});const buffer=await audio.decodeAudioData(await file.arrayBuffer());if(id!==generation)return;if(buffer.duration>120||buffer.numberOfChannels>2)throw Error('Use mono or stereo narration of at most 120 seconds.');narration=buffer;narrationName=file.name.slice(0,120);$('movie-audio-status').textContent=`${narrationName} · ${buffer.duration.toFixed(1)} seconds, loaded locally.`;if(scenes.length)audioNote(readPlan());
      }catch(e){if(id===generation){narration=null;$('movie-audio-status').textContent=e.message;}}finally{if(audio)await audio.close();if(id===generation){audioLoading=false;controls(!!state);}}
    };
    $('movie-fit').onclick=()=>{try{if(!narration)throw Error('Add a narration audio file first.');const p=readPlan(),factor=narration.duration/p.seconds;const durations=scenes.map(s=>s.enabled?s.duration*factor:s.duration);if(durations.some((d,i)=>scenes[i].enabled&&(d<0.5||d>15)))throw Error('Fitted scenes need 0.5–15 seconds each. Change the scene selection first.');scenes.forEach((s,i)=>s.duration=durations[i]);renderScenes();status('Timing fitted proportionally. Preview and adjust scene boundaries to match the spoken words.');}catch(e){status(e.message);}};
    async function start(record){let s;try{
      if(state)return;const p=readPlan();if(narration&&narration.duration>p.seconds+0.15)throw Error('Narration is longer than the video. Fit timing before recording.');
      const Audio=root.AudioContext||root.webkitAudioContext;if(!Audio)throw Error('Web Audio is unavailable in this browser.');
      if(record&&(!root.MediaRecorder||!canvas.captureStream))throw Error('Video recording is unavailable in this browser.');
      clearOutput();const audio=new Audio();s={audio,dest:audio.createMediaStreamDestination(),nodes:[],plan:p,token:generation,finished:false,discard:false};state=s;controls(true);await audio.resume();if(state!==s||s.discard)return;
      const master=audio.createGain();master.gain.value=0.8;master.connect(s.dest);master.connect(audio.destination);
      if(record){const types=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'],mimeType=types.find(t=>MediaRecorder.isTypeSupported(t));if(!mimeType)throw Error('No supported recording format. Try desktop Chromium.');
        s.stream=canvas.captureStream(30);for(const track of s.dest.stream.getAudioTracks())s.stream.addTrack(track.clone());const chunks=[];let bytes=0;s.recorder=new MediaRecorder(s.stream,{mimeType,videoBitsPerSecond:4000000});
        s.recorder.ondataavailable=e=>{if(e.data.size){bytes+=e.data.size;if(bytes>50*1024*1024){s.discard=true;stop(true);status('Recording exceeded 50 MB. Choose a shorter script.');}else chunks.push(e.data);}};
        s.recorder.onerror=()=>{s.discard=true;stop(true);status('Recording failed. Try a shorter script or another browser.');};
        s.recorder.onstop=()=>{cleanup(s);if(s.discard||s.token!==generation)return;blob=new Blob(chunks,{type:mimeType});if(!blob.size){status('Recording was empty. Try again.');return;}url=URL.createObjectURL(blob);$('movie-preview').src=url;$('movie-download').hidden=false;controls(false);status(s.early?'Partial recording ready. Preview it before saving.':'Video ready. Preview the audio, captions and source visibility before saving.');};s.recorder.start(250);
      }
      s.start=audio.currentTime+0.12;
      // A silent source keeps an audio track present even without narration/music.
      const silent=audio.createConstantSource(),zero=audio.createGain();zero.gain.value=0;silent.connect(zero);zero.connect(master);silent.start(s.start);silent.stop(s.start+p.seconds);s.nodes.push(silent);
      if(narration){const voice=audio.createBufferSource();voice.buffer=narration;voice.connect(master);voice.start(s.start);s.nodes.push(voice);}
      if($('movie-music').checked)for(const scene of p.scenes){const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type='sine';oscillator.frequency.value=[130.81,164.81,196,174.61][scene.index%4];gain.gain.setValueAtTime(0,s.start+scene.start);gain.gain.linearRampToValueAtTime(0.065,s.start+scene.start+0.08);gain.gain.setValueAtTime(0.065,s.start+scene.end-0.12);gain.gain.linearRampToValueAtTime(0,s.start+scene.end);oscillator.connect(gain);gain.connect(master);oscillator.start(s.start+scene.start);oscillator.stop(s.start+scene.end);s.nodes.push(oscillator);}
      let last=-1;function frame(){if(state!==s||s.discard)return;const elapsed=Math.max(0,audio.currentTime-s.start),scene=CodeAliveMovie.draw(ctx,p,elapsed);$('movie-position').textContent=`Scene ${scene.index+1}/${p.scenes.length} · ${Math.min(elapsed,p.seconds).toFixed(1)} / ${p.seconds.toFixed(1)}s`;if(scene.index!==last){last=scene.index;onRange(scene.range);}if(elapsed>=p.seconds){s.finished=true;stop();return;}s.raf=requestAnimationFrame(frame);}frame();s.watchdog=setTimeout(()=>{if(state===s){stop(true);status('Playback stalled. Keep this view visible and try again.');}},(p.seconds+8)*1000);status(record?'Recording in real time. Keep this view visible.':'Previewing narration and scene timing.');
    }catch(e){if(s){s.discard=true;if(s.recorder?.state==='recording')s.recorder.stop();else cleanup(s);}status(e.message);}}
    $('movie-play').onclick=()=>start(false);$('movie-record').onclick=()=>start(true);$('movie-stop').onclick=()=>stop();
    $('movie-save').onclick=()=>{if(!blob)return;if(host){const reader=new FileReader();reader.onload=()=>host.postMessage({type:'saveExplanationVideo',base64:String(reader.result).split(',')[1],format:blob.type.includes('mp4')?'mp4':'webm'});reader.onerror=()=>status('Could not read the recording.');reader.readAsDataURL(blob);}else{const a=document.createElement('a');a.href=url;a.download='codealive-explanation.'+(blob.type.includes('mp4')?'mp4':'webm');a.click();}};
    document.addEventListener('visibilitychange',()=>{if(document.hidden&&state){stop(true);status('Stopped because the view was hidden. Keep it visible during preview or recording.');}});
    return {clear,setContext(){setContext();stepRange();},getBlob:()=>blob,getState:()=>state?{recording:!!state.recorder,seconds:state.plan.seconds}:null};
  }};
})(globalThis);
